### ISSUE TITLE
spacemacs folding functions not work anymore when evil-vimish-fold-mode enabled

### ISSUE THREAD

**Issue by kelvinh** [alexmurray/evil-vimish-fold#6]
Thanks to this great package and also `vimish-fold`, now I can create fold in Emacs manually!

But this is a minor problem: I am using **spacemacs**, and by default there are already some folding functions, bound to `zc`(close fold), `zo`(open fold), `zm`(close all folds), `zr`(open all folds). Take a **.c** file for example, when I press `zm`, all functions in the buffer will be folded, but when I enable `evil-vimish-fold-mode`, I can create fold with `zf`, but the original folding functions do not work anymore, am I doing something wrong?

**Comment by alexmurray** [comment]
evil-vimish-fold integrates `evil`'s folding commands to work via the `vimish-fold` - whereas it sounds like spacemacs must integrate these `zm` / `zc` etc to work via some other system - so I am assuming when you enable `evil-vimish-fold-mode this overrides the integration that spacemacs had set up - since there can only be one active user of the `evil` folding commands, `evil-vimish-fold` wins - so I don't think there is an easy way to achieve what you want - unless spacemacs changes to use `vimish-fold` internally instead of whatever other folding implementation it is currently using.

**Comment by kelvinh** [comment]
OK, thanks for your great explanation, it's clear now.
